Install yq and jq

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -51,13 +51,23 @@ runs:
     - shell: bash
       id: proxy
       run: |-
-        echo '${{ toJSON(inputs.outputs) }}'
-        echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json
-        echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json | jq . -c -M -e
-        JSON=$(echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json | jq . -c -M -e)
-        echo "result=${JSON}"
-        echo "result=${JSON}" >> $GITHUB_OUTPUT
+        if echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json ; then 
+            echo '${{ toJSON(inputs.outputs) }}'
+            echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json
+            echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json | jq . -c -M -e
 
+
+          JSON=$(echo '${{ toJSON(inputs.outputs) }}' | yq 'with(select(. != ""); .=from_yaml) | with(select(. == ""); .={})' -o json | jq . -c -M -e)
+          echo "result=${JSON}"
+          echo "result=${JSON}" >> $GITHUB_OUTPUT
+        else
+          echo "Validation Error!!!"
+          echo "Outputs is not valid YAML"
+        
+          echo '${{ inputs.outputs }}'
+          exit 1;
+        fi
+        
     - uses: cloudposse/github-action-yaml-config-query@0.1.1
       id: mask
       with:
